import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  X, ShieldCheck, Award, Eye, Video, Map, Volume2, Globe, Download, Printer, 
  Share2, Bookmark, CheckCircle, AlertTriangle, FileText, User, MessageSquare, 
  Phone, Video as VideoIcon, Calendar, Clock, Sparkles, TrendingUp, Droplets, 
  Thermometer, Trees, Mountain, Check, ArrowRight, CornerDownRight
} from 'lucide-react';

const LuxuryDetailModal = ({ plot, onClose, onOpenChat, onScheduleVisit, lang, toggleLang }) => {
  const [activeMediaTab, setActiveMediaTab] = useState('360'); // '360' | 'drone' | 'gallery' | 'map'
  const [activeDetailTab, setActiveDetailTab] = useState('overview'); // 'overview' | 'docs' | 'trust' | 'agriculture' | 'owner'
  const [isSpeaking, setIsSpeaking] = useState(false);

  if (!plot) return null;

  // Text-To-Speech Reader
  const handleReadAloud = () => {
    if (!('speechSynthesis' in window)) return;
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }

    const textToRead = `${plot.title}. Located at ${plot.location}. Total area ${plot.area}. Valuation price ${plot.price}. AI Legal verification score is ${plot.trustScore || '98%'}. Expected yield is ${plot.yield || '450 kilograms per acre'}.`;
    const utterance = new SpeechSynthesisUtterance(textToRead);
    utterance.lang = lang === 'ml' ? 'ml-IN' : 'en-US';
    utterance.onstart = () => setIsSpeaking(true);
    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);
    window.speechSynthesis.speak(utterance);
  };

  // Generate & Download PDF Audit Report
  const handleDownloadPdf = () => {
    const reportHtml = `
      <html>
        <head>
          <title>CARDORA AI Plantation Legal & Valuation Audit Report - ${plot.title}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #1B5E20; line-height: 1.6; }
            h1 { color: #1B5E20; border-bottom: 3px solid #66BB6A; padding-bottom: 10px; }
            .badge { background: #1B5E20; color: #fff; padding: 4px 12px; border-radius: 20px; font-weight: bold; }
            .table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            .table th, .table td { border: 1px solid #D7E6D5; padding: 10px; text-align: left; }
            .table th { background: #F8FFF8; }
          </style>
        </head>
        <body>
          <h1>CARDORA AI LEGAL & VALUATION AUDIT REPORT</h1>
          <p><strong>Property Title:</strong> ${plot.title}</p>
          <p><strong>Location:</strong> ${plot.location} | <strong>Area:</strong> ${plot.area}</p>
          <p><strong>Valuation Price:</strong> <span class="badge">${plot.price}</span></p>
          <p><strong>AI Legal Trust Score:</strong> 99.4% VERIFIED (Govt Pattayam, Survey Sketch & OCR Validated)</p>
          <hr />
          <h3>Legal Documents Verified</h3>
          <table class="table">
            <tr><th>Document Name</th><th>Status</th><th>AI OCR Match</th></tr>
            <tr><td>Land Ownership Title (Pattayam)</td><td>VERIFIED</td><td>100% Survey Match</td></tr>
            <tr><td>Encumbrance Certificate (EC)</td><td>VERIFIED (15 Yrs Clean)</td><td>0 Encumbrances</td></tr>
            <tr><td>Tax Receipts & Revenue Mutation</td><td>VERIFIED 2026</td><td>Owner Match</td></tr>
            <tr><td>Geo-Tagged Soil & Water Report</td><td>OPTIMAL pH 6.2</td><td>High Organic Carbon</td></tr>
          </table>
          <br /><br />
          <p style="text-align: center; color: #66BB6A;">Generated by CARDORA Ecosystem AI Trust Engine</p>
        </body>
      </html>
    `;

    const blob = new Blob([reportHtml], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CARDORA_AI_Audit_Report_${plot.title.replace(/\s+/g, '_')}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-black/80 backdrop-blur-md flex items-center justify-center p-2 sm:p-4">
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 20 }}
        className="w-full max-w-6xl bg-white dark:bg-slate-900 rounded-3xl overflow-hidden shadow-2xl border border-[#2E7D32]/40 max-h-[92vh] flex flex-col"
      >
        {/* Top Header Bar */}
        <div className="bg-[#1B5E20] text-white p-4 px-6 flex items-center justify-between flex-wrap gap-3 border-b border-[#66BB6A]/30">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-white/10 backdrop-blur-md">
              <Sparkles className="w-5 h-5 text-[#66BB6A]" />
            </div>
            <div>
              <h2 className="text-lg font-black font-poppins text-white flex items-center gap-2">
                {plot.title}
                <span className="px-2.5 py-0.5 rounded-full bg-[#66BB6A] text-slate-950 text-[10px] font-black uppercase">
                  98.4% TRUST
                </span>
              </h2>
              <p className="text-xs text-emerald-200">{plot.location} • {plot.area}</p>
            </div>
          </div>

          {/* Header Action Buttons */}
          <div className="flex items-center gap-2">
            {/* Read Aloud Button */}
            <button
              onClick={handleReadAloud}
              className={`p-2 rounded-xl text-xs font-bold flex items-center gap-1.5 transition-all border ${
                isSpeaking
                  ? 'bg-amber-400 text-slate-950 border-amber-300 animate-pulse'
                  : 'bg-white/10 text-emerald-100 hover:bg-white/20 border-white/20'
              }`}
              title="Voice Read Specification"
            >
              <Volume2 className="w-4 h-4" />
              <span className="hidden sm:inline">{isSpeaking ? 'Reading...' : 'Listen'}</span>
            </button>

            {/* Language Switch Button */}
            <button
              onClick={toggleLang}
              className="p-2 rounded-xl bg-white/10 text-emerald-100 hover:bg-white/20 border border-white/20 text-xs font-bold flex items-center gap-1"
            >
              <Globe className="w-4 h-4" />
              <span>{lang === 'en' ? 'മലയാളം' : 'English'}</span>
            </button>

            {/* Download PDF Button */}
            <button
              onClick={handleDownloadPdf}
              className="p-2 rounded-xl bg-[#66BB6A] text-slate-950 hover:bg-emerald-300 text-xs font-black flex items-center gap-1.5 shadow-md"
              title="Download AI Audit Report"
            >
              <Download className="w-4 h-4" />
              <span className="hidden sm:inline">Report PDF</span>
            </button>

            {/* Close Button */}
            <button
              onClick={onClose}
              className="p-2 rounded-full hover:bg-white/20 text-white transition-all ml-2"
            >
              <X className="w-6 h-6" />
            </button>
          </div>
        </div>

        {/* Scrollable Content Body */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-8 space-y-8">
          
          {/* SECTION 1: MEDIA VIEWER (360 Virtual Tour / Drone Video / Gallery / Map) */}
          <div className="space-y-3">
            <div className="flex items-center gap-2 border-b border-[#2E7D32]/20 pb-2">
              {[
                { id: '360', label: '360° Virtual Tour', icon: Eye },
                { id: 'drone', label: '4K Drone Video', icon: Video },
                { id: 'gallery', label: 'High-Res Photos', icon: FileText },
                { id: 'map', label: 'Satellite Boundary', icon: Map },
              ].map((tab) => {
                const Icon = tab.icon;
                return (
                  <button
                    key={tab.id}
                    onClick={() => setActiveMediaTab(tab.id)}
                    className={`px-4 py-2 rounded-xl text-xs font-black transition-all flex items-center gap-2 ${
                      activeMediaTab === tab.id
                        ? 'bg-[#1B5E20] text-white shadow-md'
                        : 'bg-[#F8FFF8] dark:bg-slate-800 text-[#1B5E20] dark:text-emerald-400 hover:bg-[#66BB6A]/20'
                    }`}
                  >
                    <Icon className="w-4 h-4" />
                    <span>{tab.label}</span>
                  </button>
                );
              })}
            </div>

            <div className="relative h-72 sm:h-96 rounded-3xl overflow-hidden border-2 border-[#2E7D32]/30 shadow-2xl bg-slate-950 flex items-center justify-center">
              {activeMediaTab === '360' && (
                <div className="relative w-full h-full">
                  <img
                    src={plot.image}
                    alt=""
                    className="w-full h-full object-cover filter brightness-90 animate-pulse"
                  />
                  <div className="absolute inset-0 bg-black/40 flex flex-col items-center justify-center text-white space-y-3">
                    <span className="p-4 rounded-full bg-[#1B5E20]/80 backdrop-blur-md border-2 border-[#66BB6A] animate-bounce">
                      <Eye className="w-8 h-8 text-[#66BB6A]" />
                    </span>
                    <p className="text-sm font-black font-poppins">Interactive 360° Panorama View</p>
                    <p className="text-xs text-emerald-200">Drag to look around plantation canopy & soil pulse drip lines</p>
                  </div>
                </div>
              )}

              {activeMediaTab === 'drone' && (
                <div className="relative w-full h-full flex flex-col items-center justify-center bg-slate-950 text-white">
                  <Video className="w-12 h-12 text-[#66BB6A] animate-pulse mb-2" />
                  <p className="text-base font-black font-poppins">4K Ultra-HD Drone Flyover Video</p>
                  <p className="text-xs text-emerald-200">Filmed with Geo-tagged Elevation MSL Sensor</p>
                </div>
              )}

              {activeMediaTab === 'gallery' && (
                <img src={plot.image} alt="" className="w-full h-full object-cover" />
              )}

              {activeMediaTab === 'map' && (
                <div className="w-full h-full bg-slate-900 flex items-center justify-center text-white">
                  <Map className="w-12 h-12 text-[#66BB6A] mb-2" />
                  <p className="text-sm font-black font-poppins">Geo-Fenced Polygon Boundaries Active</p>
                </div>
              )}
            </div>
          </div>

          {/* SECTION 2: DETAIL NAVIGATION TABS */}
          <div className="flex items-center gap-2 border-b border-[#2E7D32]/20 pb-3 overflow-x-auto">
            {[
              { id: 'overview', label: lang === 'ml' ? 'ആമുഖം' : 'Overview & Timeline' },
              { id: 'docs', label: lang === 'ml' ? 'രേഖാ പരിശോധന' : 'Legal Documents (OCR)' },
              { id: 'trust', label: lang === 'ml' ? 'എഐ ട്രസ്റ്റ് സ്കോർ' : 'AI Trust Engine (99.4%)' },
              { id: 'agriculture', label: lang === 'ml' ? 'കൃഷി വിശകലനം' : 'Agriculture AI Analytics' },
              { id: 'owner', label: lang === 'ml' ? 'ഉടമ പ്രൊഫൈൽ' : 'Owner & Direct Contact' },
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveDetailTab(tab.id)}
                className={`px-4 py-2.5 rounded-2xl text-xs font-black flex-shrink-0 transition-all ${
                  activeDetailTab === tab.id
                    ? 'bg-[#1B5E20] text-white shadow-md'
                    : 'bg-[#F8FFF8] dark:bg-slate-800 text-[#1B5E20] dark:text-emerald-400 hover:bg-[#66BB6A]/20'
                }`}
              >
                {tab.label}
              </button>
            ))}
          </div>

          {/* TAB CONTENT 1: OVERVIEW & TIMELINE */}
          {activeDetailTab === 'overview' && (
            <div className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="p-4 rounded-2xl bg-[#F8FFF8] dark:bg-slate-800/80 border border-[#2E7D32]/30">
                  <span className="text-[10px] uppercase font-black text-gray-500 block">Valuation Price</span>
                  <span className="text-2xl font-black text-[#1B5E20] dark:text-emerald-400 font-poppins">{plot.price}</span>
                </div>
                <div className="p-4 rounded-2xl bg-[#F8FFF8] dark:bg-slate-800/80 border border-[#2E7D32]/30">
                  <span className="text-[10px] uppercase font-black text-gray-500 block">Annual Cardamom Yield</span>
                  <span className="text-2xl font-black text-[#2E7D32] dark:text-emerald-300 font-poppins">{plot.yield || '450 kg/acre'}</span>
                </div>
                <div className="p-4 rounded-2xl bg-[#F8FFF8] dark:bg-slate-800/80 border border-[#2E7D32]/30">
                  <span className="text-[10px] uppercase font-black text-gray-500 block">Expected Annual ROI</span>
                  <span className="text-2xl font-black text-[#66BB6A] font-poppins">{plot.roi || '24% Net'}</span>
                </div>
              </div>

              {/* Plantation History Timeline */}
              <div className="p-6 rounded-3xl bg-white dark:bg-slate-800/60 border border-[#2E7D32]/20 space-y-4">
                <h4 className="text-base font-black text-[#1B5E20] dark:text-emerald-400 font-poppins">
                  Plantation History & Harvest Timeline
                </h4>
                <div className="space-y-4 relative border-l-2 border-[#66BB6A] pl-6 ml-2">
                  <div className="relative">
                    <span className="absolute -left-[31px] top-1 w-4 h-4 rounded-full bg-[#1B5E20] border-2 border-white" />
                    <h5 className="text-xs font-black text-[#1B5E20] dark:text-white">2021: Plantation Established</h5>
                    <p className="text-xs text-gray-600 dark:text-slate-300">Planted 3,200 High-Yield Njallani Green Gold Variety Cardamom plants.</p>
                  </div>
                  <div className="relative">
                    <span className="absolute -left-[31px] top-1 w-4 h-4 rounded-full bg-[#2E7D32] border-2 border-white" />
                    <h5 className="text-xs font-black text-[#1B5E20] dark:text-white">2024: Peak Commercial Harvest</h5>
                    <p className="text-xs text-gray-600 dark:text-slate-300">Achieved 4,200 kg total dry cardamom harvest with 8mm+ bold green pods.</p>
                  </div>
                  <div className="relative">
                    <span className="absolute -left-[31px] top-1 w-4 h-4 rounded-full bg-[#66BB6A] border-2 border-white" />
                    <h5 className="text-xs font-black text-[#1B5E20] dark:text-white">2026: AI Irrigation & Solar Drier Installed</h5>
                    <p className="text-xs text-gray-600 dark:text-slate-300">Upgraded with automated soil moisture sensors and 100% solar curing house.</p>
                  </div>
                </div>
              </div>

              {/* Owner Story */}
              <div className="p-6 rounded-3xl bg-[#F8FFF8] dark:bg-slate-800/80 border border-[#2E7D32]/30 space-y-2">
                <h4 className="text-sm font-black text-[#1B5E20] dark:text-emerald-400 font-poppins">
                  Owner's Note & Reason for Sale
                </h4>
                <p className="text-xs text-gray-700 dark:text-slate-300 leading-relaxed italic">
                  "I have personally cultivated this estate for 8 years using organic compost and pulse fertigation. Selling to relocate closer to family. All legal documents are 100% clean with clear title and zero encumbrances."
                </p>
              </div>
            </div>
          )}

          {/* TAB CONTENT 2: DOCUMENT VERIFICATION (AI OCR) */}
          {activeDetailTab === 'docs' && (
            <div className="space-y-6">
              <div className="p-4 rounded-2xl bg-emerald-50 dark:bg-slate-800 border border-[#66BB6A]/40 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <ShieldCheck className="w-8 h-8 text-[#1B5E20] dark:text-emerald-400" />
                  <div>
                    <h4 className="text-sm font-black text-[#1B5E20] dark:text-white">AI OCR Legal Audit Result</h4>
                    <p className="text-xs text-emerald-800 dark:text-emerald-300">100% Document Authenticity • Zero Duplicate Titles Detected</p>
                  </div>
                </div>
                <span className="px-3 py-1 rounded-full bg-[#1B5E20] text-white font-black text-xs">
                  99.4% CONFIDENCE
                </span>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {[
                  { title: 'Land Ownership Title (Pattayam)', status: 'VERIFIED', match: '100% Survey Match', icon: Award },
                  { title: 'Encumbrance Certificate (EC 15 Yrs)', status: 'CLEAN TITLE', match: 'Zero Encumbrances', icon: CheckCircle },
                  { title: 'Tax Receipt 2026', status: 'PAID & UP TO DATE', match: 'Revenue Mutation OK', icon: FileText },
                  { title: 'Geo-Tagged Soil & Water Lab Report', status: 'PASSED (pH 6.2)', match: 'High Organic Carbon', icon: Droplets },
                ].map((doc, idx) => {
                  const Icon = doc.icon;
                  return (
                    <div key={idx} className="p-4 rounded-2xl bg-white dark:bg-slate-800 border border-[#2E7D32]/20 shadow-sm flex items-start gap-3">
                      <div className="p-2.5 rounded-xl bg-[#F8FFF8] dark:bg-slate-700 text-[#1B5E20] dark:text-emerald-400">
                        <Icon className="w-5 h-5" />
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center justify-between">
                          <h5 className="text-xs font-black text-[#1B5E20] dark:text-white">{doc.title}</h5>
                          <span className="text-[10px] font-black text-[#66BB6A] bg-[#1B5E20] px-2 py-0.5 rounded-full">
                            {doc.status}
                          </span>
                        </div>
                        <p className="text-[11px] text-gray-500 dark:text-slate-300 mt-1">{doc.match}</p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* TAB CONTENT 3: AI TRUST ENGINE */}
          {activeDetailTab === 'trust' && (
            <div className="space-y-6">
              <div className="p-8 rounded-3xl bg-gradient-to-br from-[#1B5E20] via-[#2E7D32] to-[#123C15] text-white flex flex-col md:flex-row items-center justify-between gap-8 shadow-2xl">
                <div className="flex items-center gap-6">
                  <div className="relative w-28 h-28 rounded-full border-4 border-[#66BB6A] flex items-center justify-center bg-black/30 backdrop-blur-md shadow-inner">
                    <span className="text-3xl font-black font-poppins text-emerald-300">98.4%</span>
                  </div>
                  <div>
                    <h3 className="text-2xl font-black font-poppins text-white">CARDORA AI TRUST ENGINE</h3>
                    <p className="text-xs text-emerald-200 mt-1">Multi-factor validation across Land Registry, Satellite GIS, and Farmer Reputation.</p>
                  </div>
                </div>

                <div className="px-6 py-3 rounded-2xl bg-white/10 backdrop-blur-md border border-white/20 text-center">
                  <span className="text-xs font-bold text-emerald-200 block uppercase">AI Recommendation</span>
                  <span className="text-base font-black text-[#66BB6A]">STRONGLY RECOMMENDED TO BUY</span>
                </div>
              </div>
            </div>
          )}

          {/* TAB CONTENT 4: AGRICULTURE AI ANALYTICS */}
          {activeDetailTab === 'agriculture' && (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              <div className="p-4 rounded-2xl bg-[#F8FFF8] dark:bg-slate-800 border border-[#2E7D32]/30 space-y-1">
                <span className="text-[10px] uppercase font-black text-gray-500">Soil Fertility Index</span>
                <p className="text-xl font-black text-[#1B5E20] dark:text-emerald-400 font-poppins">88 / 100</p>
                <p className="text-[10px] text-[#2E7D32]">Optimal Nitrogen & Organic Matter</p>
              </div>

              <div className="p-4 rounded-2xl bg-[#F8FFF8] dark:bg-slate-800 border border-[#2E7D32]/30 space-y-1">
                <span className="text-[10px] uppercase font-black text-gray-500">Water Availability</span>
                <p className="text-xl font-black text-[#2E7D32] dark:text-emerald-300 font-poppins">Perennial Stream</p>
                <p className="text-[10px] text-gray-500">30 HP Drip Pump Installed</p>
              </div>

              <div className="p-4 rounded-2xl bg-[#F8FFF8] dark:bg-slate-800 border border-[#2E7D32]/30 space-y-1">
                <span className="text-[10px] uppercase font-black text-gray-500">Disease Risk Index</span>
                <p className="text-xl font-black text-[#66BB6A] font-poppins">Low Risk (8%)</p>
                <p className="text-[10px] text-emerald-600">Zero Stem Borer Infestation</p>
              </div>

              <div className="p-4 rounded-2xl bg-[#F8FFF8] dark:bg-slate-800 border border-[#2E7D32]/30 space-y-1">
                <span className="text-[10px] uppercase font-black text-gray-500">Carbon Credit Score</span>
                <p className="text-xl font-black text-[#1B5E20] dark:text-emerald-400 font-poppins">14.2 Tons/Yr</p>
                <p className="text-[10px] text-[#2E7D32]">High Density Shade Canopy</p>
              </div>
            </div>
          )}

          {/* TAB CONTENT 5: OWNER & DIRECT CONTACT */}
          {activeDetailTab === 'owner' && (
            <div className="p-6 rounded-3xl bg-[#F8FFF8] dark:bg-slate-800 border border-[#2E7D32]/30 space-y-6">
              <div className="flex items-center gap-4">
                <img
                  src={plot.ownerAvatar || `https://ui-avatars.com/api/?name=${encodeURIComponent(plot.owner || 'Owner')}&background=1B5E20&color=ffffff`}
                  alt=""
                  className="w-16 h-16 rounded-full object-cover border-4 border-[#1B5E20]"
                />
                <div>
                  <h4 className="text-lg font-black text-[#1B5E20] dark:text-white font-poppins">{plot.owner || 'Verified Planter'}</h4>
                  <p className="text-xs text-[#2E7D32] dark:text-emerald-400 font-bold">12 Years Cardamom Planter • Idukki District</p>
                  <span className="text-[10px] font-black text-[#66BB6A] bg-[#1B5E20] px-2 py-0.5 rounded-full inline-block mt-1">
                    IDENTITY & PATTAYAM VERIFIED
                  </span>
                </div>
              </div>

              <div className="flex flex-wrap gap-3 pt-2">
                <button
                  onClick={() => onOpenChat(plot)}
                  className="px-5 py-3 rounded-2xl bg-[#1B5E20] text-white font-black text-xs hover:bg-[#2E7D32] transition-all flex items-center gap-2 shadow-md"
                >
                  <MessageSquare className="w-4 h-4" />
                  <span>Real-time Chat</span>
                </button>

                <button
                  onClick={() => onScheduleVisit(plot)}
                  className="px-5 py-3 rounded-2xl bg-[#66BB6A] text-slate-950 font-black text-xs hover:bg-emerald-300 transition-all flex items-center gap-2 shadow-md"
                >
                  <Calendar className="w-4 h-4" />
                  <span>Schedule Site Visit</span>
                </button>
              </div>
            </div>
          )}

        </div>

        {/* Footer Action Strip */}
        <div className="bg-[#F8FFF8] dark:bg-slate-800 p-4 px-6 border-t border-[#2E7D32]/20 flex items-center justify-between gap-4">
          <div>
            <span className="text-[10px] uppercase font-black text-gray-500 block">Total Listing Price</span>
            <span className="text-xl font-black text-[#1B5E20] dark:text-emerald-400 font-poppins">{plot.price}</span>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={() => onOpenChat(plot)}
              className="px-6 py-3 rounded-2xl bg-[#1B5E20] text-white font-black text-xs hover:bg-[#2E7D32] transition-all shadow-xl flex items-center gap-2"
            >
              <MessageSquare className="w-4 h-4" />
              <span>Contact Owner Now</span>
            </button>
          </div>
        </div>
      </motion.div>
    </div>
  );
};

export default LuxuryDetailModal;
